### ISSUE TITLE
Let's Rebuild the Pahal Website for New upcoming first year!!!

### ISSUE THREAD

**Issue by swastkk** [istenith/pahal#16]
Change the stylings and add the necesary things in this year's PAHAL Website!!

Signed-off-by:  swastkk@gmail.com

**Comment by codesmith25103** [comment]
Want to work on this issue. Can you please assign me this issue?

**Comment by Jasleen-001** [comment]
Hey,can i work on this issue?

**Comment by swastkk** [comment]
Marked as Done,
Pahal 2022 is going to be on 7, 8, 9th November.
