### ISSUE TITLE
Update content of faq pug/pages/faq.pug

### ISSUE THREAD

**Issue by rathod-sahaab** [istenith/pahal#8]
should be short and easy language

**Comment by srijan-kapoor** [comment]
Hi @Rathod-Sahaab! Could you provide few sample set of questions to give a better idea on what could be added to FAQs? I'm interested.

**Comment by rathod-sahaab** [comment]
Sure, @notpluto. These won't be about the website but the questions people/generally face during admissions. Some questions are already added to `pug/pages/faq.pug`. This page will only concern with admission related questions.
General advices should be saved for Advisory section
Thanks for your help!
